name: "php-cs-fixer"

on: [push]

jobs:
  php-cs-fixer:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: "--allow-risky=yes --using-cache=no"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "php-cs-fixer"